name: mom6-tools-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - nbsphinx
  - numpy
  - numpydoc
  - pip
  - python=3.7
  - recommonmark
  - sphinx_rtd_theme
  - sphinx>=1.6
  - xarray
  - netcdf4
  - numba
  - scipy
  - jinja2
  - dask
  - pyyaml
  - cmocean
  - pytest
  - cartopy
  - cftime
  - matplotlib
  - netCDF4
  - pip:
    - sphinx_copybutton
